[phases.setup]
nixPkgs = ["nodejs_20", "caddy"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "caddy fmt --overwrite Caddyfile"
]

[start]
cmd = "caddy run --config Caddyfile"
