name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: TypeScript type check
      run: npm run check
    
    - name: Build verification
      run: npm run build
    
    - name: Verify build artifacts
      run: |
        if [ ! -f "dist/index.js" ]; then
          echo "❌ Backend build failed - dist/index.js not found"
          exit 1
        fi
        if [ ! -d "dist/public" ]; then
          echo "❌ Frontend build failed - dist/public not found"
          exit 1
        fi
        echo "✅ All build artifacts verified successfully"
